[package]
name = "tana_lang_test"
version = "0.1.0"
edition = "2021"
authors = ["tana-gh <yozoranotakaku@gmail.com>"]
description = "Tests for Tana Language."

[dependencies]
tana_lang_codegen = { path = "../tana_lang_codegen" }
